#import "conf.typ": *

#import "@preview/hydra:0.6.1": hydra

#show: ut-thesis.with(
    title: "Filler Title",
    author: "John Doe",
    degree: "Doctor of Philosophy",
    dedication: "This thesis is dedicated to the single most important person.",
    quote_page: (
        attribution: "Abraham Lincoln",
        body: "Bad promises are better broken than kept.",
    ),
    // You could also have multiple quotes by putting them in a list like this:
    // quote_page: (
    //     (
    //         attribution: "Author One",
    //         body: "Quote One",
    //     ),
    //     (
    //         attribution: "Author Two",
    //         body: "Quote Two"
    //     ),
    // )
    abstract: [
        #lorem(200)
    ],
)


= First Chapter
== Subsection for the Table of Contents
Just to show what references look like @newton1833philosophiae. I also need some filler text because I want to show that the main text is properly double spaced between lines.
#figure(
    box(fill: red, height: 5cm, width: 5cm, stroke: black + 1mm),
    caption: [Red Box. However, to show that the text in a caption is not double spaced I need some more filler text.],
)
=== Subsubsection is even smaller.
#figure(
    table(
        columns: 2,
        "data", "extra",
        "more data",
    ),
    caption: [Data generated by an experiment I conducted.],
)
= A second Chapter
With second chapter stuff.

#show: ut-thesis-appendix
= Some Extra Stuff
An appendix for all the loose ends you didn't want to distract in the main body.

#bibliography("bib.bib", style: "american-physics-society")
