#import "conf.typ": *

#import "@preview/hydra:0.6.1": hydra

// You can use parenthesis to put information in or surround it with square
// brackets.
#show: ut-thesis.with(
    title: "Filler Title",
    author: "Author Authorson",
    degree: [Doctor of Philosophy],
    department: [Based Living],
    dedication: "This thesis is dedicated to the single most important person.",
    quote_page: (
        attribution: "Abraham Lincoln",
        body: "Bad promises are better broken than kept.",
    ),
    // You could also have multiple quotes by putting them in a list like this:
    // quote_page: (
    //     (
    //         attribution: "Author One",
    //         body: "Quote One",
    //     ),
    //     (
    //         attribution: "Author Two",
    //         body: "Quote Two"
    //     ),
    // )
    acknowledgements: [This thesis is for all my day ones who supported me.],
    abstract: [
        #lorem(200)
    ],
)

= Introduction
Typst is a document generation software comparable to Latex. It is different by employing a simpler markdown inspired syntax and has a more powerful scripting language that powers it, as opposed to the custom macro based framework in Latex. I started using it due to the real-time rendering capabilities it provided compared to Overleaf, and what really made me stick with it was how easy I found it to be to create more complicated layouts and functions. I ended up writing my thesis for the University of Toronto in Typst and wanted to share the template I used that resulted in a document that was approved by the School of Graduate Studies (SGS). It is *not* officially sponsored by SGS as opposed to the Latex or Word templates.

== Subsection for the Table of Contents
Just to show what references look like @newton1833philosophiae. I also need some filler text because I want to show that the main text is properly double spaced between lines.
#figure(
    box(fill: red, height: 5cm, width: 5cm, stroke: black + 1mm),
    caption: [Red Box. However, to show that the text in a caption is not double spaced I need some more filler text.],
)
=== Subsubsection is even smaller.
#figure(
    table(
        columns: 2,
        "data", "extra",
        "more data",
    ),
    caption: [Data generated by an experiment I conducted. See the #link("https://typst.app/docs/guides/table-guide/")[table guide] on Typst documentation for better formatting.],
)

// Here is how you can separate your thesis into multiple documents. The only
// requirement is that the file be located in the same directory as the thesis
// file.
#include "second_chapter.typ"

= Conclusion
There is a light at the end of the tunnel.

#show: ut-thesis-appendix
= Some Extra Stuff
An appendix for all the loose ends you didn't want to distract in the main body.

#bibliography("bib.bib", style: "american-physics-society")
